name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to server
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to VPS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ideatecore
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          # Update PATH to include NVM binaries
          export PATH=$PATH:/root/.nvm/v22.12.0/bin

          # Debugging information
          echo $PATH
          which npm
          which pm2

          # Commands
          cd /home/ideatecore/IDE-Indonesia/IDE-client
          git pull origin main
          npm install
          npm run build
          pm2 restart /home/ideatecore/IDE-Indonesia/ecosystem.config.cjs
        debug: true
